name: schedule_alerts

on:
  workflow_dispatch:
  schedule:
  - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        AWS_REGION_NAME: ${{secrets.AWS_REGION_NAME}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}
        EMAIL_SENDER: ${{secrets.EMAIL_SENDER }}
        EMAIL_SENDER_PASSWORD: ${{secrets.EMAIL_SENDER_PASSWORD }}
        run: echo "The API key is:${{secrets.EMAIL_SENDER}}"

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # Install the python version needed

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
      
      
      - name: Execute Python script # Run the app.py
#         run: |
#           SCRAPING_HUB_KEY=${{secrets.SCRAPING_HUB_KEY }}  python handler.py
        run: python main.py
